baseurl = "/"
languageCode = "pt-BR"
title = "Preda Qualis"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
[[menu.main]]
    name = "Início"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Metodologia"
    url = "/metodos/"
    weight = 2    
[[menu.main]]
    name = "Lista de predatórios"
    url = "/lista/"
    weight = 3
[[menu.main]]
    name = "Resumo Executivo"
    url = "/resumo/"
    weight = 4
[[menu.main]]
    name = "Resultados"
    url = "/resultados/"
    weight = 5
[[menu.main]]
    name = "Notícias"
    url = "/noticias/"
    weight = 6
[[menu.main]]
    name = "Autores"
    url = "/autores/"
    weight = 7
[params]
    description = "Periódicos potencialmente predatórios no QUALIS-CAPES"
    footer = "[Paulo Inácio Prado](http://ecologia.ib.usp.br/let/doku.php?id=engl:prado:start),  [Roberto André Kraenkel](http://www.ift.unesp.br/users/kraenkel/) & [Renato Mendes Coutinho](http://professor.ufabc.edu.br/~renato.coutinho/) 2017 | [Github](https://github.com/piklprado/predQualisHugo) "

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
