---
title: Home
---

```{r setup, echo=FALSE, warning=FALSE, message=F}
library(knitr)
#library(ggplot2)
#library(VennDiagram)
#library(googleVis)
#library(DT)
op <- options(gvis.plot.tag='chart')
opts_chunk$set(fig.align = 'center', fig.show = 'hold', fig.height = 4,
               warning = FALSE, message = FALSE, error = FALSE, echo=FALSE)
options(formatR.arrow = TRUE,width = 90, cache=TRUE)
#source("../static/verifica_predadores_qualis.R")
```

# Bem-vindo(a)

Este é o sítio de um levantamento iniciado em novembro de 2017
para:

* Identificar periódicos potencialmente fraudulentos listados pelo Sistema QUALIS-CAPES;
* Estimar a proporção destes periódicos na base QUALIS;
* Estimar a chance destes periódicos serem detectados pelo sistema QUALIS.

# IMPORTANTE

* A lista de títulos potencialmente predatórios que compilamos **não é uma palavra final** 
e está em constante revisão. 
Apresentamos estes resultados como um ferramenta para apoio ao aperfeiçoamento dos critérios
de avaliação dos programas de pós-gradução.
* O fato de um artigo ser publicado em uma revista potencialmente predatória **não
significa** que este artigo seja de má qualidade. 
Um dos prejuízos causados pelos periódicos predatórios é justamente 
potencialmente afetar a credibilidade de tais artigos.
* Caso verifique qualquer problema ou tenha sugestões sobre trabalho 
entre em contato com os autores.

## O QUALIS

[QUALIS](https://qualis.capes.gov.br/) é a classificação de todos os periódicos em que participantes dos programas de pós-graduação
do Brasil publicam seus artigos. A base é usada na avaliação da produção científica, um dos
principais critérios para [Avaliação Quadrienal dos Programa de Pós-Graduação](http://avaliacaoquadrienal.capes.gov.br/), 
feita pela CAPES.

As coordenações de cada área de conhecimento da CAPES são responsáveis por 
compilar os títulos de todos os periódicos em que orientadores, estudantes e egressos
dos programas da área publicaram artigos.
Cada área então classifica cada periódico em uma escala de relevância que vai de
A1 (mais alta), A2, B1 a B5 e C (mais baixa). 
Um mesmo título pode receber classificações diferentes em diferentes áreas. 

#### Para saber mais sobre QUALIS

* Barata, R.C.B. 2016. Dez coisas que você deveria saber sobre o QUALIS. [Revista Bras. de Pós-Graduação.](http://ojs.rbpg.capes.gov.br/index.php/rbpg/article/view/947)
* [Perguntas frequentes sobre o QUALIS](http://www.capes.gov.br/acessoainformacao/perguntas-frequentes/avaliacao-da-pos-graduacao/7422-qualis), do site da CAPES.
* [Sobre o QUALIS](https://www.sibi.usp.br/apoio-pesquisador/escrita-publicacao-cientifica/selecao-revistas-publicacao/qualis-periodicos/), da página do Sistema de Bibliotecas da USP.

## Periódicos predatórios

São revistas que cobram para publicar artigos acadêmicos, 
mas não fazem a avaliação adequada da qualidade dos textos científicos.
Esta revisão deve ser feita por pareceristas independentes que atuam na área
e acompanhada por um editor da revista, também com formação científica.

Por ser criteriosa, frequentemente envolver mais de uma rodada de revisões e muitas vezes
depender do trabalho voluntário de revisores e editores, a revisão correta 
de um artigo até a decisão de publicá-lo demora meses. 
Já os periódicos predatórios e aceitam artigos rápido e sem critério. 
Assim, burlam um dos princípios fundamentais que a ciência
tem para zelar pela qualidade do conhecimento que produz e traz a público.

#### Para saber mais sobre periódicos predatórios

* [Comittee on Publication Ethics](https://publicationethics.org/)
* [Predatory Journals, Wikipedia](https://en.wikipedia.org/wiki/Predatory_open_access_publishing)
* [Directory of Open Access Journals](https://doaj.org/), uma certificação de boas práticas para periódicos de acesso aberto
* [Cobertura sobre periódicos predatórios](http://www.diretodaciencia.com/tag/periodicos-predatorios/) do blog *Direto da Ciência*





</br>
<p style="text-align: right;"> *Última atualização: `r format(Sys.time(), '%d de %B de %Y, %H:%m')` h* </p>


